media: _posts
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ cover, title ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
  - name: config
    label: Jekyll config
    type: file
    path: _config.yml