name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - master  # Replace with your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Ruby manually
      - name: Set up Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          ruby -v
          gem install bundler

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          echo "jekyll ${{ secrets.JEKYLL_VERSION }}" > Gemfile.lock
          bundle install

      # Step 4: Build the Jekyll site
      - name: Build site with Jekyll
        run: bundle exec jekyll build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
          rsync -av --delete _site/ gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy Jekyll site [skip ci]" || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
