name: Jekyll CI and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Build the Jekyll site in a Docker container
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      # Upload the build artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages  # This is the required environment for GitHub Pages
    permissions:
      pages: write        # Required for deploying to GitHub Pages
      id-token: write     # Required for GitHub OIDC authentication
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
